services:
  todo-db:
    image: mysql:8
    container_name: taskmaster_todo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: taskmaster_todo_db
    ports:
      - "3302:3306"
    volumes:
      - todo-db-data:/var/lib/mysql
    networks:
      - backend_network

  todo-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: taskmaster_todo
    ports:
      - "4002:4002"
    depends_on:
      - todo-db
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
    networks:
      - backend_network

volumes:
  todo-db-data:

networks:
  backend_network:
    external: true
